In [1]:
import torch

In [2]:
# uniform distribution
torch.rand(4)

tensor([0.2467, 0.6106, 0.0498, 0.3232])

In [3]:
# normal distribution
torch.randn(2,2)

tensor([[-0.2429, -0.3656],
        [ 0.8981,  0.1785]])

In [4]:
# range random integer
torch.randint(1,10,(2,4))

tensor([[3, 6, 8, 2],
        [7, 1, 2, 3]])

In [5]:
x=torch.autograd.Variable(torch.Tensor([2]),requires_grad=True)
w=torch.autograd.Variable(torch.Tensor([3]),requires_grad=True)

b=torch.autograd.Variable(torch.Tensor([4]), requires_grad=True)

In [6]:
y=x*w+b*b

In [7]:
y.backward()

In [8]:
b.grad

tensor([8.])

In [9]:
x.grad_fn

## Simple Network

In [10]:
data = torch.linspace(1,60,)+torch.randn()

In [17]:
input_size=100
hidden_size=200
output_size=10

In [15]:
torch.nn.Sequential(
    torch.nn.Linear(input_size,hidden_size),
    torch.nn.Sigmoid(),
    torch.nn.Linear(hidden_size, output_size)
                   )

NameError: name 'output_size' is not defined